import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTables1731846516963 implements MigrationInterface {
    name = 'CreateTables1731846516963'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "habitlog" ("_id" SERIAL NOT NULL, "date" date NOT NULL, "completed" boolean NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "habit_id" integer, CONSTRAINT "PK_b2030c47c12b2db33519469ea71" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TABLE "habit" ("_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(255) NOT NULL, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp(6) with time zone, CONSTRAINT "PK_7e40f94a2204515a3ade0222e06" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`ALTER TABLE "habitlog" ADD CONSTRAINT "FK_a06dde2181b27c1320e2aefefe4" FOREIGN KEY ("habit_id") REFERENCES "habit"("_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "habitlog" DROP CONSTRAINT "FK_a06dde2181b27c1320e2aefefe4"`);
        await queryRunner.query(`DROP TABLE "habit"`);
        await queryRunner.query(`DROP TABLE "habitlog"`);
    }

}
